FROM hope/base-alpine:3.4

MAINTAINER Sergey Sadovoi <sergey@hope.ua>

ENV SHOUTCAST_VERSION=2.4.7

RUN \
    apk add --no-cache --virtual=build-dependencies wget ca-certificates && \
    cd "/tmp" && \

    # Install glibc
    # https://github.com/andyshinn/alpine-pkg-glibc
  #  wget -q -O /etc/apk/keys/andyshinn.rsa.pub https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/andyshinn.rsa.pub && \
  #  apk --no-cache -X http://apkproxy.heroku.com/andyshinn/alpine-pkg-glibc add glibc && \

    # Install ShoutCast
    wget http://download.nullsoft.com/shoutcast/tools/sc_serv2_linux_x64-latest.tar.gz && \
    mkdir -p /usr/local/shoutcast && \
    tar -xzf sc_serv2_linux_x64-latest.tar.gz -C /usr/local/shoutcast && \

    # Cleanup
    apk del build-dependencies && \
    rm "/tmp/"*

ONBUILD COPY container-files/sc.conf /usr/local/shoutcast/sc.conf

EXPOSE 7777
EXPOSE 7778

WORKDIR /usr/local/shoutcast

ENTRYPOINT ["./sc_serv"]
CMD ["./sc.conf"]
